version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5005:5005"  # デバッグポート
    volumes:
      - ./:/app
      - sqlite-data:/app/data
      - ~/.m2:/root/.m2  # Mavenキャッシュの共有
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/app.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  sqlite-data:
