version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - sqlite-data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped

volumes:
  sqlite-data:
